[package]
name = "launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
octocrab = "0.38.0"
reqwest = { version = "0.12.4", features = ["blocking", "json"] }
tokio = { version = "1.38.0", features = ["full"] }
zip = "2.1.3"

[build-dependencies]
winresource = "0.1.17"

